/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    DynamicDialog: typeof import('primevue/dynamicdialog')['default']
    Menu: typeof import('primevue/menu')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
