/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "logout": [],
    "password.email": [],
    "password.update": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirmation": [],
    "password.confirm": [],
    "sanctum.csrf-cookie": [],
    "api.tasks.index": [],
    "api.tasks.store": [],
    "api.tasks.show": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.update": [
        {
            "name": "task",
            "required": true
        }
    ],
    "api.tasks.destroy": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.index": [],
    "api.categories.store": [],
    "api.tags.index": [],
    "api.tags.store": [],
    "api.subtasks.index": [],
    "api.subtasks.store": [],
    "api.subtasks.destroy": [
        {
            "name": "subtask",
            "required": true,
            "binding": "id"
        }
    ],
    "api.reminder.store": [],
    "api.reminder.destroy": [
        {
            "name": "reminder",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.comment.store": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.tag.store": [
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "api.tasks.tag.destroy": [
        {
            "name": "task",
            "required": true
        },
        {
            "name": "tag",
            "required": true
        }
    ],
    "tasks.index": [],
    "tasks.create": [],
    "tasks.store": [],
    "tasks.show": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.edit": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.update": [
        {
            "name": "task",
            "required": true
        }
    ],
    "tasks.destroy": [
        {
            "name": "task",
            "required": true
        }
    ]
}
}
export {};
